[package]
name = "trees"
version = "0.1.2"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT/Apache-2.0"
keywords = [ "tree", "forest", "linked", "collection", "simple" ]
readme = "README.md"
repository = "https://github.com/oooutlk/trees"
documentation = "https://docs.rs/trees"
categories = [ "data-structures", "no-std" ]
description = "expressing tree-like data structures conveniently and compactly"
