[package]
name = "trees"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT OR Apache-2.0"
description = "storing and manipulating tree-like data the simple way"
repository = "https://github.com/oooutlk/trees"
readme = "README.md"
keywords = [ "tree", "forest", "linked", "sibling", "simple" ]
categories = [ "data-structures", "no-std" ]
