[package]
name = "trees"
version = "0.1.3"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT/Apache-2.0"
keywords = [ "tree", "forest", "linked", "collection", "simple" ]
readme = "README.md"
repository = "https://github.com/oooutlk/trees"
documentation = "https://docs.rs/trees"
categories = [ "data-structures", "no-std" ]
description = "a fundamental library for storing and manipulating tree-like data structures"
